//! End-to-end tests: pulling from an authenticated private registry.
//!
//! This is the path that `RegistryAuth` on `ContainerConfig` exists for, and
//! the one place where "the credentials were wired up" and "the credentials
//! work" genuinely differ — everything else about a pull looks identical
//! whether or not auth was applied.
//!
//! The fixture stands up a real `registry:2` with htpasswd basic auth, pushes
//! a payload image into it, and deletes the local copy so the engine has no
//! choice but to pull. The negative test is what gives the positive one its
//! meaning: the same pipeline without credentials must fail.
//!
//! Docker treats `localhost` registries as insecure-by-default, so no TLS or
//! daemon configuration is involved. Logins use an isolated `DOCKER_CONFIG`
//! so the developer's own credential store is never touched.

use crate::e2e_support::{require_docker, run_pipeline_with_secrets, stage_names};
use std::collections::HashMap;
use std::process::Command;
use tempfile::TempDir;

const REGISTRY_PORT: u16 = 5959;
const REGISTRY_USER: &str = "oxide";
const REGISTRY_PASSWORD: &str = "s3cret-registry-pw";
/// Small, ubiquitous, and irrelevant to the test beyond having a shell.
const PAYLOAD_SOURCE: &str = "alpine:3.20";

fn docker(args: &[&str]) -> std::process::Output {
    Command::new("docker")
        .args(args)
        .output()
        .expect("docker should be invokable")
}

/// A private registry that cleans itself up.
struct PrivateRegistry {
    container: String,
    image: String,
    _workdir: TempDir,
}

impl PrivateRegistry {
    fn start(name: &str) -> Self {
        let workdir = TempDir::new().unwrap();
        let auth_dir = workdir.path().join("auth");
        let config_dir = workdir.path().join("config");
        std::fs::create_dir_all(&auth_dir).unwrap();
        std::fs::create_dir_all(&config_dir).unwrap();

        // htpasswd with bcrypt, generated by the httpd image so the host needs
        // no apache tooling of its own.
        let htpasswd = docker(&[
            "run",
            "--rm",
            "httpd:2-alpine",
            "htpasswd",
            "-Bbn",
            REGISTRY_USER,
            REGISTRY_PASSWORD,
        ]);
        assert!(
            htpasswd.status.success(),
            "failed to generate htpasswd: {}",
            String::from_utf8_lossy(&htpasswd.stderr)
        );
        std::fs::write(auth_dir.join("htpasswd"), &htpasswd.stdout).unwrap();

        let container = format!("oxide-e2e-registry-{name}");
        // A leftover from an interrupted run would hold the port.
        docker(&["rm", "-f", &container]);

        let started = docker(&[
            "run",
            "-d",
            "--name",
            &container,
            "-p",
            &format!("{REGISTRY_PORT}:5000"),
            "-v",
            &format!("{}:/auth", auth_dir.display()),
            "-e",
            "REGISTRY_AUTH=htpasswd",
            "-e",
            "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm",
            "-e",
            "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd",
            "registry:2",
        ]);
        assert!(
            started.status.success(),
            "failed to start registry: {}",
            String::from_utf8_lossy(&started.stderr)
        );

        let registry = Self {
            container,
            image: format!("localhost:{REGISTRY_PORT}/oxide/payload:v1"),
            _workdir: workdir,
        };

        // A successful login doubles as the readiness probe.
        let config = config_dir.display().to_string();
        let mut logged_in = false;
        for _ in 0..30 {
            let attempt = Command::new("docker")
                .env("DOCKER_CONFIG", &config)
                .args([
                    "login",
                    &format!("localhost:{REGISTRY_PORT}"),
                    "-u",
                    REGISTRY_USER,
                    "-p",
                    REGISTRY_PASSWORD,
                ])
                .output()
                .expect("docker should be invokable");
            if attempt.status.success() {
                logged_in = true;
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(300));
        }
        assert!(logged_in, "registry never became ready");

        assert!(
            docker(&["pull", "-q", PAYLOAD_SOURCE]).status.success(),
            "failed to pull the payload source image"
        );
        assert!(
            docker(&["tag", PAYLOAD_SOURCE, &registry.image])
                .status
                .success(),
            "failed to tag the payload image"
        );
        let pushed = Command::new("docker")
            .env("DOCKER_CONFIG", &config)
            .args(["push", "-q", &registry.image])
            .output()
            .expect("docker should be invokable");
        assert!(
            pushed.status.success(),
            "failed to push the payload image: {}",
            String::from_utf8_lossy(&pushed.stderr)
        );

        // Delete the local copy: the engine must go to the registry for it,
        // which is the entire point.
        registry.forget_local_image();
        registry
    }

    fn forget_local_image(&self) {
        docker(&["rmi", "-f", &self.image]);
    }

    fn image_is_present_locally(&self) -> bool {
        docker(&["image", "inspect", &self.image]).status.success()
    }
}

impl Drop for PrivateRegistry {
    fn drop(&mut self) {
        docker(&["rm", "-f", &self.container]);
        docker(&["rmi", "-f", &self.image]);
    }
}

/// A pipeline whose single step runs the payload image, optionally declaring
/// registry credentials.
fn pipeline_yaml(image: &str, with_credentials: bool) -> String {
    let registry_block = if with_credentials {
        format!(
            "            registry:\n              url: localhost:{REGISTRY_PORT}\n              username: {REGISTRY_USER}\n              password_secret: REGISTRY_PASSWORD\n"
        )
    } else {
        String::new()
    };

    format!(
        r#"name: private-registry-e2e
version: "1"
stages:
  - name: run
    steps:
      - name: from-private-registry
        run: |
          echo pulled-and-ran
        environment:
          type: container
          container:
            image: {image}
{registry_block}"#
    )
}

fn registry_secrets() -> HashMap<String, String> {
    let mut secrets = HashMap::new();
    secrets.insert(
        "REGISTRY_PASSWORD".to_string(),
        REGISTRY_PASSWORD.to_string(),
    );
    secrets
}

#[test]
fn private_registry_pull_succeeds_with_credentials() {
    require_docker();

    let registry = PrivateRegistry::start("ok");
    assert!(
        !registry.image_is_present_locally(),
        "the payload image must be absent locally, or this proves nothing"
    );

    let workspace = TempDir::new().unwrap();
    let yaml = pipeline_yaml(&registry.image, true);

    let result = run_pipeline_with_secrets(&yaml, workspace.path(), registry_secrets());

    assert!(
        result.success,
        "the engine should authenticate and pull; stages were {:?}",
        stage_names(&result)
    );
    assert!(
        registry.image_is_present_locally(),
        "the image should now be present locally, having been pulled"
    );
}

#[test]
fn private_registry_pull_fails_without_credentials() {
    require_docker();

    // Without this the positive test above would pass just as happily against
    // a registry that never checked anything.
    let registry = PrivateRegistry::start("denied");
    assert!(!registry.image_is_present_locally());

    let workspace = TempDir::new().unwrap();
    let yaml = pipeline_yaml(&registry.image, false);

    let result = run_pipeline_with_secrets(&yaml, workspace.path(), registry_secrets());

    assert!(
        !result.success,
        "an unauthenticated pull from a private registry must fail"
    );
    assert!(
        !registry.image_is_present_locally(),
        "nothing should have been pulled"
    );
}
