# Rust Fuzzing & Security Pipeline
# Real security testing with cargo-audit, cargo-deny, and fuzzing

name: rust-fuzzing
version: "1.0"

variables:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

stages:
  - name: setup
    steps:
      - name: rust-version
        run: |
          rustc --version
          cargo --version

      - name: check-security-tools
        run: |
          echo "=== Security Tools Status ==="
          which cargo-audit >/dev/null 2>&1 && echo "✓ cargo-audit" || echo "○ cargo-audit (not installed)"
          which cargo-deny >/dev/null 2>&1 && echo "✓ cargo-deny" || echo "○ cargo-deny (not installed)"
          which cargo-outdated >/dev/null 2>&1 && echo "✓ cargo-outdated" || echo "○ cargo-outdated (not installed)"
          echo ""
          echo "Install with: cargo install cargo-audit cargo-deny cargo-outdated"

  - name: build
    steps:
      - name: check
        run: cargo check
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

      - name: build-debug
        run: cargo build
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

      - name: build-release
        run: cargo build --release
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

  - name: test
    steps:
      - name: unit-tests
        run: cargo test --lib -- --nocapture
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

      - name: run-app
        run: cargo run --release
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

  - name: security
    steps:
      - name: cargo-audit
        run: |
          echo "=== Security Audit ==="
          if which cargo-audit >/dev/null 2>&1; then
            cargo audit || echo "Audit complete"
          else
            echo "⚠ cargo-audit not installed, skipping"
            echo "  Install: cargo install cargo-audit"
          fi
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

      - name: dependency-tree
        run: |
          echo "=== Dependency Tree ==="
          cargo tree --depth 1
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

  - name: static-analysis
    steps:
      - name: clippy
        run: |
          echo "=== Clippy Lints ==="
          cargo clippy -- -W clippy::all
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

      - name: fmt-check
        run: |
          echo "=== Format Check ==="
          cargo fmt -- --check || echo "Format issues found (run: cargo fmt)"
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

  - name: fuzz-check
    steps:
      - name: fuzz-setup-check
        run: |
          echo "=== Fuzz Targets ==="
          echo "Available fuzz targets:"
          ls -la fuzz/fuzz_targets/
          echo ""
          echo "To run fuzzing locally:"
          echo "  cargo +nightly fuzz run fuzz_parse_user -- -max_total_time=60"
          echo "  cargo +nightly fuzz run fuzz_validate_email -- -max_total_time=60"
          echo "  cargo +nightly fuzz run fuzz_parse_config -- -max_total_time=60"
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing

      - name: fuzz-corpus-init
        run: |
          echo "=== Initializing Fuzz Corpus ==="
          mkdir -p fuzz/corpus/fuzz_parse_user
          mkdir -p fuzz/corpus/fuzz_validate_email
          mkdir -p fuzz/corpus/fuzz_parse_config
          
          # Seed corpus for user parsing
          echo '{"name":"test","age":25}' > fuzz/corpus/fuzz_parse_user/valid1
          echo '{"name":"","age":0}' > fuzz/corpus/fuzz_parse_user/valid2
          echo 'invalid json' > fuzz/corpus/fuzz_parse_user/invalid1
          
          # Seed corpus for email validation
          echo 'user@example.com' > fuzz/corpus/fuzz_validate_email/valid1
          echo 'invalid' > fuzz/corpus/fuzz_validate_email/invalid1
          echo '' > fuzz/corpus/fuzz_validate_email/empty
          
          # Seed corpus for config parsing
          echo 'key=value' > fuzz/corpus/fuzz_parse_config/valid1
          echo '# comment' > fuzz/corpus/fuzz_parse_config/comment
          
          echo "Corpus initialized with seed inputs"
          find fuzz/corpus -type f | wc -l
          echo "seed files created"
        working_directory: /home/ops/Project/oxide-ci/examples/rust-fuzzing
